server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/


spring:
  application:
    name: spring-cloud-eureka