server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/

spring:
  application:
    name: spring-cloud-eureka
