spring:
  application:
    name: zuul
server:
  port: 9400
zuul:
  routes:
    api-a:
      path: /producer/**
      serviceId: spring-cloud-producer

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/

