server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
          defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/


spring:
  application:
    name: spring-cloud-eureka